name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution Unique Name (no spaces)'
        required: true
        default: BCOverdueNotifierSolution

      solution_exported_folder:
        description: 'Do not change'
        required: true
        default: out/exported

      solution_folder:
        description: 'Do not change'
        required: true
        default: out/solutions

      solution_target_folder:
        description: 'Do not change'
        required: true
        default: solutions

env:
  ENVIRONMENT_URL: https://operations-ciellos-sandbox-1.crm.dynamics.com
  CLIENT_ID: 7e103436-2b7a-40f7-ac94-02b97ff278c7
  TENANT_ID: 46e85934-1fab-4533-a4ad-de92ce1fd81a

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Who Am I
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}

    - name: Export Solution (Unmanaged)
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip
        managed: false

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
        solution-type: Unmanaged
        overwrite-files: true

    - name: Create Branch & Commit
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder }}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
